config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'
  resources :surveys, only: [:show, :new, :create, :index] do 
    resources :responses, only: [:new, :create, :index]
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :survey
  belongs_to :question
  belongs_to :response
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy

  validates :text, presence: true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy
  belongs_to :user

  def self.to_csv(survey_id, options = {})
    responses = Response.where(survey_id: survey_id)
    CSV.generate(options) do |csv|
      csv << ["Timestamp", "User"] + Survey.find(survey_id).questions.map { |q| "Q" + q.qid.to_s }
      responses.each do |r|
        datum = []
        datum[0] = r.created_at
        datum[1] = r.user.name
        r.answers.each do |a|
          datum[a.question.qid + 1] = a.str_value
        end
        csv << datum
      end
    end
  end

  accepts_nested_attributes_for :answers
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :survey_users
  has_many :participants, class_name: "User", through: :survey_users, source: :user
  belongs_to :researcher, class_name: "User", foreign_key: "researcher_id"

  accepts_nested_attributes_for :questions

  validates :name, presence: true
end

app/models/survey_user.rb
class SurveyUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :created_surveys, class_name: "Survey", foreign_key: "researcher_id", dependent: :destroy
  has_many :assigned_surveys, through: :survey_users, source: :survey
  has_many :survey_users
  has_many :responses
  has_many :answers

  enum role: {participant: 0, researcher: 1, admin: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :name])
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_participant, only: [:new, :create]
  before_action :correct_researcher, only: [:index]
  def new
    @survey = Survey.find(params[:survey_id])
    @response = @survey.responses.build
    @survey.questions.each { |q| @response.answers.build(survey_id: @survey.id, question_id: q.id) }

  end
  def create
    @survey = Survey.find(params[:survey_id])
    @response = @survey.responses.build(response_params)
    @response.user = current_user
    if @response.save
      flash[:notice] = 'Response recorded!'
      redirect_to @survey
    else
      flash[:alert] = "Oops, something went wrong!"
      render :new
    end
  end
  def index
    @survey = Survey.find(params[:survey_id])
    @responses = @survey.responses
    @data = []
    @responses.each do |r|
      datum = []
      datum[0] = r.created_at
      datum[1] = r.user.name
      r.answers.each do |a|
        datum[a.question.qid + 1] = a.str_value
      end
      @data << datum
    end
    respond_to do |format|
      format.html
      format.csv { send_data @responses.to_csv(@survey.id) }
    end
  end
  private
  def response_params
    params.require(:response).permit(:answers_attributes => [:question_id, :survey_id, :num_value, :str_value, :bool_value])
  end
  def correct_participant
    @survey = current_user.assigned_surveys.find_by(id: params[:survey_id])
    redirect_to :index if @survey.nil? || current_user.researcher?
  end
  def correct_researcher
    @survey = current_user.created_surveys.find_by(id: params[:survey_id])
    redirect_to :index if @survey.nil? || current_user.participant?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_researcher, only: [:new, :create]
  before_action :correct_participant_or_researcher, only: [:show]

  def index
    if current_user.researcher?
      @surveys = current_user.created_surveys
    elsif current_user.participant?
      @surveys = current_user.assigned_surveys
    elsif current_user.admin?
      @surveys = Survey.all
    end
  end
  def show
    @survey = Survey.find(params[:id])
  end
  def new
    @survey = Survey.new
    3.times { @survey.questions.build }
    @participants = User.where(role: :participant)
  end
  def create
    @survey = current_user.created_surveys.build(survey_params)
    if @survey.save
      flash[:notice] = 'Survey created!'
      redirect_to survey_path(@survey)
   else
      flash[:alert] = 'Oops, something went wrong!'
      @participants = User.where(role: :participant)
      render :new
   end
  end
  private
  def survey_params
    params.require(:survey).permit(:name, :description, participant_ids: [], :questions_attributes => [:qid, :text, :details, :input_type, :options])
  end
  def correct_researcher
    redirect_to action: :index if current_user.participant?
  end
  def correct_participant_or_researcher
    if current_user.participant?
      @survey = current_user.assigned_surveys.find_by(id: params[:id])
      redirect_to action: :index if @survey.nil?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dcaasrails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "auth-action" %>
      <% else %>
      <%= link_to "Sign in", new_user_session_path, class: "auth-action" %>
      <% end %>
    <%= yield %>
  </div>
  <div class="col-md-3"></div>
</div>

</body>
</html>

app/views/responses/index.html.erb
<h1><%= @survey.name %> data</h1>

<table class="table table-condensed">
  <tr>
    <td><b>Timestamp</b></td>
    <td><b>User</b></td>
    <% @survey.questions.each do |q| %>
      <td><b>Q<%= q.qid %></b></td>
    <% end %>
  </tr>
  <% @data.each do |datum| %>
    <tr>
      <td>
        <%= datum[0] %>
      </td>
      <td>
        <%= datum[1] %>
      </td>

      <% @survey.questions.each do |q| %>
        <td>
          <% if datum[q.qid+1] %>
            <%= datum[q.qid+1] %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<%= link_to "Export to CSV", survey_responses_path(survey_id: @survey.id, format: "csv"), class: "btn btn-default"  %> 
<%= link_to "Return to the survey", survey_path(@survey), class: "btn btn-default" %>

app/views/responses/new.html.erb
<h1><%= @survey.name %></h1>
<p><%= @survey.description %></p><br>
<%= form_for([@survey, @response], html: {class: "post-form" }) do |f| %>
    <!-- <%= render 'shared/error_messages', object: @response %> -->
    <% @response.answers.each do |answer| %>
        <%= f.fields_for :answers, answer do |builder| %>
          <%= builder.label :str_value, answer.question.text %>
          <p><%= answer.question.details %> </p>
          <%= builder.text_field :str_value, class: "form-control" %>
          <%= builder.hidden_field :survey_id, value: @survey.id %>
          <%= builder.hidden_field :question_id, value: answer.question.id %>
          <br>
        <% end %>
    <% end %>
    <div class="actions">
      <%= f.submit class: "btn btn-default" %> <%= link_to "Go back", @survey, class: "btn btn-default" %>
    </div>
 <% end %>

app/views/shared/_error_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="error"><%= msg %></li>
    <% end %>
  </ul> 
<% end %>

app/views/static_pages/home.html.erb
<h1>Data Collection</h1>

<% if user_signed_in? %>
<%= link_to "All surveys", surveys_path %>
<% end %>

<p>Welcome to our data collection platform! Here, you will be able to administer, manage, and take surveys
in a secure, anonymous way.</p>

app/views/surveys/index.html.erb
<h1>All surveys</h1><br>
<% if @surveys %>
<table class="table table-condensed">
  <tr>
    <td><b>Index</b></td>
    <td><b>Name</b></td>
    <td><b>Description</b></td>
  </tr>
  <% @surveys.each_with_index do |survey, index| %>
   <tr>
     <td><%= index+1 %></td>
     <td><%= link_to survey.name, survey_path(survey) %></td>
     <td><%= survey.description %></td>
   </tr>
  <% end %>
</table>
<% else %>
  <p>Aw, shucks, you don't have a survey yet!</p>
<% end %>

<% if current_user.researcher? %>
<%= link_to "Create a survey", new_survey_path, class: "btn btn-default" %>
<% end %>

app/views/surveys/new.html.erb
<h1>Create a new survey</h1>
<%= form_for(@survey) do |f| %>
  <%= render 'shared/error_messages', object: @survey %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control"  %><hr>
  </div>
  <div class="field">
    <%= f.label :description, style: "margin-top: 10px;" %><br>
    <%= f.text_area :description, class: "form-control"  %><hr>
  </div>
  <% qid = 1 %>
  <% @survey.questions.each.with_index do |question, index| %>
   <%= f.fields_for :questions, question do |builder| %>
    <p>
      <%= builder.label :text, "Question " + (index+1).to_s, style: "margin-top: 10px;" %><br/>
      <%= builder.text_area :text, :row => 3, class: "form-control"  %>
      <%= builder.label :details, style: "margin-top: 10px;" %>
      <%= builder.text_area :details, class: "form-control"  %><hr>

      <%= builder.hidden_field :qid, value: qid %>
    </p>
  <% end %>
    <% qid += 1 %>
  <% end %>
  <div class="field">
    <%= f.label :participant_ids, 'Participants', style: "margin-top: 16px;" %><br>
    <%= f.select :participant_ids, options_from_collection_for_select(@participants, "id", "name"), { prompt: "Please select"}, { multiple: true, class: "form-control" }  %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default", style: "margin-top: 10px; margin-bottom: 20px" %>
  </div>
<% end %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>
<%= @survey.description %>
<br><br>
<table class="table table-condensed">
  <tr>
    <td><b>Question</b></td>
    <td><b>Details</b></td>
  </tr>
  <% for question in @survey.questions %>
    <tr>
      <td><%= question.text %></td>
      <td><%= question.details %></td>
    </tr>
  <% end %>
</table>
<% if current_user.participant? %>
<%= link_to "Take survey", new_survey_response_path(survey_id: @survey.id), class: "btn btn-default"  %>
<% end %>
<% if current_user.researcher? %>
<%= link_to "See answers", survey_responses_path(survey_id: @survey.id), class: "btn btn-default" %>
<% end %>
<%= link_to "All surveys", surveys_path, class: "btn btn-default" %>